# Author: Dzhuneyt (https://dzhuneyt.com)
# Originally published at: https://github.com/Dzhuneyt/home-assistant-blueprints
# License: MIT

blueprint:
  name: AC Turn On Comfort Mode
  description: >
    When any specified AC is switched to a specified mode, switch it to another specified mode and set a preset temperature.
  domain: automation
  input:
    climate_entity:
      name: Climate Entity
      description: The climate entity whose HVAC mode changes to monitor, and whose HVAC mode and temperature to change.
      selector:
        entity:
          domain: climate
    when_hvac_mode_detected:
      name: Trigger Mode
      description: "The mode that triggers the automation. Usually: auto"
      default: auto
      selector:
        select:
          options:
            - auto
            - heat
            - cool
            - dry
            - fan_only
    hvac_mode:
      name: HVAC Mode
      description: The HVAC mode to switch to when the HVAC mode is moved to the trigger mode. Depending on the current season, this is usually "heat" during winter and "cool" during summer.
      selector:
        select:
          options:
            - heat
            - cool
    temperature:
      name: Temperature
      description: The temperature to set when switching modes.
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input climate_entity
    to: !input when_hvac_mode_detected

action:
  - service: climate.set_temperature
    data:
      hvac_mode: !input hvac_mode
      temperature: !input temperature
    target:
      entity_id: !input climate_entity

mode: single
